### PR TITLE
Add endpoints

### PR DESCRIPTION
**Pull request by Stephenitis**
Hello guys,

There are a number of options that we needed to add to give your users for flexibility with our service

- endpoint
- api version

Ideally we would like users to default to and change these later if we can add a select dropdown for these options via the Segment UI that would be most helpful for your users.

```js
apiVersion: "1"
endpoint : "mq-aws-us-east-1.iron.io"
```

integrations - ironioiron-production 2015-01-28 15-29-58

selfie-1

stephen@iron.io

### CODE REVIEW

**Comment by Stephenitis** [comment]
selfie-1

**Comment by Stephenitis** [comment]
if we can pre populate a list of endpoints for the user and attach specific endpoints to api versions it would be much helpful. @fortyfivian

**Comment by ysadka** [comment]
Hey guys, any update on this?

**Comment by amillet89** [comment]
hey @Stephenitis @ysadka sorry for the delay. currently we don't have ability to do conditional settings but adding that to the queue. For time being I'm inclined to add a dropdown for API version and a text field for the endpoint. What are the different API versions we should make available? Thanks for the PR!

**Comment by Stephenitis** [comment]
hey @amillet89 

api versions are 1 and 3

**Comment by Stephenitis** [comment]
The region/endpoint is a value that we can bring to the user to fill in

**Comment by amillet89** [comment]
ok cool, and in the interest of migrating existing customers, what's the default value for the region? https://mq-aws-us-east-1.iron.io:443 ?

**Comment by amillet89** [comment]
@Stephenitis

**Comment by ysadka** [comment]
@amillet89 yes, that would be the default value...thanks!

**Comment by amillet89** [comment]
alrighty changes merged and deployed! sorry for the delay and thanks for the gif :)

**Pull request merged**
